apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: bloodconnect-prod

resources:
  - ../../base

replicas:
  - name: bloodconnect-app
    count: 3

images:
  - name: yourdockerhubuser/bloodconnect
    newTag: latest
